## Numpy Array and Basics 

Learn about Numpy

In [2]:
import numpy as np

## Creating Array from List

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1-D Array : ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2-D Array : ", arr_2d)


1-D Array :  [1 2 3 4 5]
2-D Array :  [[1 2 3]
 [4 5 6]]


## List versus Numpy

In [12]:
py_list = [1,2,3]
print("Python List Multiplication : ", py_list * 2)
np_array = np.array([1,2,3])  ## Element Wise multiplication
print("Python Array Multiplication : ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation Time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Operation Time : ", time.time() - start)


Python List Multiplication :  [1, 2, 3, 1, 2, 3]
Python Array Multiplication :  [2 4 6]

 List Operation Time :  0.08180761337280273

 Numpy Operation Time :  0.0019388198852539062


### Creating Array from Scratch 

In [13]:
zeros = np.zeros((3,5))
print("Zeros Array : \n",zeros)

Zeros Array : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
ones = np.ones((34,438))
print("Ones Array : \n", ones)

Ones Array : 
 [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [15]:
full = np.full((2,2), 7)
print("Full Array : \n", full)

Full Array : 
 [[7 7]
 [7 7]]


In [ ]:
### Most used, RANDOM ARRAY 
random = np.random.random()