## Numpy Array Operations 

In [1]:
import numpy as np

In [3]:
## Indexing 
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing : ", arr[2 : 7])
print("With step : ", arr[1:8:2])
print("Negative Indexing : ", arr[-3])

Basic Slicing :  [3 4 5 6 7]
With step :  [2 4 6 8]
Negative Indexing :  8


In [8]:
## Indexing in 2-d Matrices
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element : ", arr_2d[1,2])  #[row, column]
print("Entire 1st Row : ", arr_2d[1]) 
print("Entire 3nd Column", arr_2d[:,2])

Specific Element :  6
Entire 1st Row :  [4 5 6]
Entire 3nd Column [3 6 9]


## Sorting 

In [ ]:
## Basic 1-D Array Sorting
unsorted = np.array([1,4,2,3,76,32,21,12,13,0])
print("Sorted Array  : ", np.sort(unsorted))


Sorted Array  :  [ 0  1  2  3  4 12 13 21 32 76]


In [12]:
## 2-D Unsorted 
arr_2d_unsorted = np.array([[3,1] ,[1,2], [2, 3]])
print("Sorted 2-D Array by Column : ", np.sort(arr_2d_unsorted, axis = 0))
print("Sorted 2-D Array by Row : ", np.sort(arr_2d_unsorted, axis = 1))

Sorted 2-D Array by Column :  [[1 1]
 [2 2]
 [3 3]]
Sorted 2-D Array by Row :  [[1 3]
 [1 2]
 [2 3]]


## Filtering 

In [15]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]  
## Numpy allow us to write expressions which can be evaluated inside the array index
print("Even Numbers : ", even_number)

Even Numbers :  [ 2  4  6  8 10]


## Filtering with Mask 

In [17]:
mask = numbers > 5
print("Numbers greater than 5 : ", numbers[mask])

Numbers greater than 5 :  [ 6  7  8  9 10]


## Fancy Indexing versus np.where()

In [19]:
indices = [0,2,4]
print(numbers[indices])

## Where Clause
where_result = np.where(numbers > 5)
print("NP Where : ", numbers[where_result])


[1 3 5]
NP Where :  [ 6  7  8  9 10]


In [ ]:
condition_Array = np.where(numbers > 5, numbers*5, numbers) ## Similar to Ternary Operator
## np.where(CONDITION, True -- > Operation, False -- > Operation)

print(condition_Array)

[ 1  2  3  4  5 30 35 40 45 50]


## Adding and Removing Data

In [25]:
## Merging two arrays 
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibilty 

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

#### VERY IMPORTANT CODE 

print("Compatibilty Shapes : ",a.shape == b.shape)

Compatibilty Shapes :  True


### Adding Rows and Columns 


In [32]:
original = np.array([[1,2,3],[4,5,6]])
new_row = np.array([7,8,9])

with_new_row = np.vstack((original, new_row))  ## vstack adds a new row
print(original)
print(with_new_row)

new_col = np.array([[32],[43]])
with_new_col = np.hstack((original, new_col))
print(original)
print(with_new_col)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3 32]
 [ 4  5  6 43]]


## Deleting Elements (Take care of Indexing)

In [34]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("Array after deletion : ",deleted)

Array after deletion :  [1 2 4 5]
