## Numpy Array and Basics 

Learn about Numpy

In [3]:
import numpy as np

## Creating Array from List

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1-D Array : ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2-D Array : ", arr_2d)


1-D Array :  [1 2 3 4 5]
2-D Array :  [[1 2 3]
 [4 5 6]]


## List versus Numpy

In [26]:
py_list = [1,2,3]
print("Python List Multiplication : ", py_list * 2)
np_array = np.array([1,2,3])  ## Element Wise multiplication
print("Python Array Multiplication : ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation Time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Operation Time : ", time.time() - start)


Python List Multiplication :  [1, 2, 3, 1, 2, 3]
Python Array Multiplication :  [2 4 6]

 List Operation Time :  0.054704904556274414

 Numpy Operation Time :  0.0039899349212646484


### Creating Array from Scratch 

In [27]:
zeros = np.zeros((3,5))
print("Zeros Array : \n",zeros)

Zeros Array : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
ones = np.ones((34,438))
print("Ones Array : \n", ones)

Ones Array : 
 [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [29]:
full = np.full((2,2), 7)
print("Full Array : \n", full)

Full Array : 
 [[7 7]
 [7 7]]


In [30]:
### Most used, RANDOM ARRAY 
random = np.random.random((2,3))
print(random)

[[0.25364823 0.42159904 0.81862569]
 [0.07186865 0.96369878 0.69988304]]


In [31]:
## Sequence 
sequence = np.arange(0,121,1)
sequence_1 = np.arange(start=0, stop=10, step=2)
print(sequence)
print(sequence_1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120]
[0 2 4 6 8]


#### VECTOR, MATRIX AND TENSOR

In [32]:
## Vector 
vector = np.array([1,2,3,4])
print("Vector : ", vector)

## Matrix
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix : ", matrix)

## Tensor
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor : ",tensor)

Vector :  [1 2 3 4]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Properties of Arrays (not lists) in Python

In [ ]:
# Initialize an array
arr = np.array([[1,2,3],
                [4,5,6]])

## PROPERTY 1 --> Shape
print("Shape : ", arr.shape)
## PROPERTY 2 --> Dimension
print("Dimension : ", arr.ndim)
## PROPERTY 3 --> Size
print("Size : ", arr.size) # Total number of elements in the array 
## PROPERTY 4 --> Data Type
print("Dtype : ", arr.dtype)


Shape :  (2, 3)
Dimension :  2
Size :  6
Dtype :  int32


## Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original Array : ", arr)

## Reshaping 
reshaped = arr.reshape((3,4)) ## If I will try to put in (3,5) , I get an error
print("Reshaped Array : ", reshaped)

## Flattening 
flattened = reshaped.flatten() ## 
print("Flattened Array : ", flattened)

## Raveled 
raveled = reshaped.ravel()#.ravel() returns VIEW (Original Array) instead of COPY
print("Raveled Array : ", raveled)

## Transpose 
transpose = reshaped.T 
print("Transposed Array : ", transpose)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
